language: python
python:
- 3.6

sudo: false
env:
  global:
    secure: "mw0HXZQuGfmQFAR5sRbglLLEVfqhi1emmi3S4RzuC7Su/d6Z+whAHpqV+BpuADdO9OURqA5BNgMaJLCdFspOZbJqTZi1agKM/cvfkMTq6IuePof6c/Peneip0n+j7OPG80vBZ0+3S2DIIlB1erPNjTnSjDE1LQkoUy8O/UObnO+gfL8cMgKmQPDm7S5YSL8n6Yqztan3spfxO1hWN57RMGRczzayR71eeEKZU1kjYijlc1D4GoSejAH2WjMkil+yLTXxNT5XKfgf85fUmVXng2XfAJc5Ea+WGzEBOc9WD0m5Hy1LngNkp+I3eBUY372maZcjo+NRFRxgfaZjGQsLqxUn0MTdK4o3iKoO+gxedjZJVnmrTLXE+cdz4xYztTucW9PfEI2P7imIw6BaPN2IKhtIw9wt/E6dhZMOZqClfxWG81F5hYOOyNUSFp1DvdLqxt1yGStpWNyXX3gE2WXKPa5itB71xyckCm7WnUFz/eM7qU2moo/YZSgUQ9LkM4MGa9U5Hnr3yrwHVklQo8VUDHwZpb9FVl0wCe4YTmH2uFnovakgtaF4h0H1zpGT8vkroQcaDvzYPqkNUajnKok4syXZyVejGuhKgbrKS2Cf3CWxHZn4ZDhYXeRZTyY+cX8sE4+s1gjbzzCaxD68eUu9EE2IGeqrmqu4lxI8UdNrQW0="

install:
- pip install mkdocs
- pip install mkdocs-material
- pip install doctr

script:
- set -e 
- mkdocs build -d site
- doctr deploy . --built-docs site/